name: Deploy CodeIgniter

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/trainingcloudexp/apps/myproject

            git config --global --add safe.directory /home/trainingcloudexp/apps/myproject

            git fetch origin
            git reset --hard origin/main
